### ISSUE TITLE
Challonge API Proxy

### ISSUE THREAD

**Issue by duk3luk3** [FAForever/faf-java-api#110]
We want tournament information in the client, but the Challonge API (https://api.challonge.com/v1) requires authentication.

The best way to solve this problem imo is to add a proxy to the API. It can be relatively simple, allowing GET requests for all authenticated users and allowing POST/PUT/DELETE only for users with Tournament Director privileges (or above).

Having some caching for GET requests would be really nice to avoid hammering the challonge api and pissing off challonge.

Making it a faithful proxy (except for the caching) would allow development in the clients to go ahead using the challonge api directly with personal challonge accounts, so I think that would be highly desirable.

**Comment by micheljung** [comment]
@duk3luk3 sounds like we could just configure nginx to do that. Any problem that wouldn't solve?

**Comment by Brutus5000** [comment]
How would you do check pmerission with nginx routing?

**Comment by micheljung** [comment]
I somehow missed that part. Nevermind me :)

**Comment by micheljung** [comment]
Actually, @Brutus5000 and @duk3luk3 , if people use their own credentials, permissions would be managed on challonge, wouldn't they? So there would be no need for the API to check any permissions.

**Comment by Brutus5000** [comment]
I thought we'd use one single account so we have all tournaments in one place (i.e. list all active tournaments in a client).

**Comment by micheljung** [comment]
@duk3luk3 https://api.dev.faforever.com/challonge/v1/tournaments.json
