### ISSUE TITLE
Mod Upload: uploaded files have wrong permissions

### ISSUE THREAD

**Issue by Brutus5000** [FAForever/faf-java-api#113]
Uploaded mods give a 403 to the user.

Reason: files created by the docker container belong to root and are not readable by others (therefore not readable by content-server).
Possible solution A: make files readable to all users.
Possible solution B: use consistent users in docker for content-server and api.

**Comment by Geosearchef** [comment]
Additionally, 402 is returned (not only on production/test, locally aswell,) 114
