### ISSUE TITLE
Filtering Issues with `_`

### ISSUE THREAD

**Issue by IDragonfire** [FAForever/faf-java-api#119]
https://github.com/FAForever/clans/issues/49

Looks like the filter has problems with `_` ...
It ignores this value ... 

Must we maybe escape it?

Example

https://japi.test.faforever.com/data/player?filter=login==Wolf_*&page[size]=20&sort=login
https://japi.test.faforever.com/data/player?filter=login==Wolf_&page[size]=20&sort=login

**Comment by micheljung** [comment]
Is it possible that there used to be a player with name `Wolf_` but there no longer is? Because I don't see an issue with the links above.

**Comment by IDragonfire** [comment]
The user has renamed, but the problem still exists .... Maybe see the forum links https://github.com/FAForever/clans/issues/49

**Comment by Brutus5000** [comment]
Seems to be solved by now.
