### ISSUE TITLE
Make use of GitHub's deployment status

### ISSUE THREAD

**Issue by micheljung** [FAForever/faf-java-api#127]

**Comment by Brutus5000** [comment]
What is the use case for this?

I had used in the python api and see no advantage for that. The deployment status is not visible on the github gui, it can only be queried using the github api.

**Comment by micheljung** [comment]
If someone, e.g. @aeoncleanse deploys a new version of a featured mod, he has no idea whether the server is actually doing something, what it is doing and when it's done. This way we can provide this information.

**Comment by Brutus5000** [comment]
As said before, you don't see it on github without manually invoking the github api.
So basically you could store the progress in the faf db and offer a route on our own api. Then you would have full control over it.

I had hoped that it would be added to a commit like travis checks etc. but this was not the case when I tested it on the python api last year.
