### ISSUE TITLE
Update to Elide 4.0 (when available)

### ISSUE THREAD

**Issue by micheljung** [FAForever/faf-java-api#140]
They fixed https://github.com/yahoo/elide/issues/387

**Comment by Brutus5000** [comment]
- [X]  SharePermission changed: remove the expression if it is not different from ReadPermission
- [X] HibernateStore removed, use AbstractHibernateStore and AbstractHibernateStore.Builder instead
- [ ] Fix error transaction now closed (maybe switch to Hibernate 5.2.x, but Spring Boot 1.5.x does not offer Hibernate 5.2.x)
