### ISSUE TITLE
Images from Api

### ISSUE THREAD

**Issue by axel1200** [FAForever/faf-java-api#149]
Allmost none of the map images is loaded in the java client:
There are two reasons for that...

1. The Url seems to be wrong

![image](https://user-images.githubusercontent.com/19996713/31773199-44039ee4-b4e2-11e7-9be4-45a0a808f14f.png)
 I don' know if I can get the image by copying its link into the brother(but I suppose that should be working)

2. Many Game Objects donot have a mapVersion

![image](https://user-images.githubusercontent.com/19996713/31773312-a12d3cba-b4e2-11e7-9048-974230e47c54.png)

**Comment by axel1200** [comment]
Is very likely to be conntected to the Server move

**Comment by axel1200** [comment]
Ok maybe point to is not valid as the player might have played a local map

**Comment by micheljung** [comment]
The URL returned by the API was https:// instead of http://. I fixed this.

We don't have https:// working yet for content.faforever.com.
