### ISSUE TITLE
7 Ladder Maps

### ISSUE THREAD

**Issue by axel1200** [FAForever/faf-java-api#187]
The api only return 7 ladder maps.....
Make the request and count maps:
https://api.faforever.com/data/ladder1v1Map/

I am pretty sure this is not correct

**Comment by Brutus5000** [comment]
The ladder1v1 is just a representation of the current pool. The pool is managed manually and contains currently 7 maps. This was not always the case, but it's the current choice.

**Comment by Brutus5000** [comment]
See this thread for further information: http://forums.faforever.com/viewtopic.php?f=2&t=13742
