### ISSUE TITLE
Number of won games wrong

### ISSUE THREAD

**Issue by axel1200** [FAForever/faf-java-api#190]
![image](https://user-images.githubusercontent.com/19996713/34217533-037f0dae-e5ac-11e7-871f-eb0afde35b0b.png)
I did the following querry, it might be that I have 18 games I dont know. But I am 100% sure I did win ladder at least once. I remember one game torpedo bomber snipping someone 😃 Must have been in Dezember 2017. Would be cool if somebody checked if it is an Api error or not correctly registered in the DB.

**Comment by axel1200** [comment]
I checked other people acctually have a number other than 0

**Comment by micheljung** [comment]
This is the server not updating the number anymore, not the API providing wrong data.
