### ISSUE TITLE
Specific error message when steam account is already linked to a different FAF account

### ISSUE THREAD

**Issue by micheljung** [FAForever/faf-java-api#193]
https://github.com/FAForever/faf-java-api/blob/0f6dadf6e3e52540deebc6aa5acc680be31cb707/src/main/java/com/faforever/api/user/UserService.java#L242

If Steam account A is already linked to a FAF account B, throw a specific error if a user tries to link Steam account A to FAF account C.

**Comment by Brutus5000** [comment]
@micheljung Did you consider this in your latest changes?

**Comment by micheljung** [comment]
Duplicated and fixed by #252
