### ISSUE TITLE
Achievments take long to load

### ISSUE THREAD

**Issue by axel1200** [FAForever/faf-java-api#194]
http://api.faforever.com/data/playerAchievement?filter=player.id==53471 takes ages make a querry parameter that allows to only request needed data..

**Comment by axel1200** [comment]
Aperently that is not fully correct, there is something else that takes to long, as achievments are generated on the fly. @micheljung  should know....

**Comment by Brutus5000** [comment]
The stated query loads within less than a second now. We did some optimizations lately. If you encounter a slow one, please open a new issue.
