### ISSUE TITLE
Events missing(players show to have to won games)

### ISSUE THREAD

**Issue by 1-alex98** [FAForever/faf-java-api#198]
The issue is about the query: api.faforever.com/data/playerEvent?filter=player.id==226577

This query suggest that the player has never won any out of his 900+ games, as UEF wins event and other are all not there. The issue occurs if I request data of other players, that means the UEF wins (and similar events) are always missing in the query if I request data about other players. If I query data about myself everything seems to be ok. Is it maybe an Security issue, that I don't have the permission to request that data?

**Comment by axel1200** [comment]
https://github.com/FAForever/downlords-faf-client/issues/718

**Comment by Brutus5000** [comment]
Not an api issue. Forwarded it to server
