### ISSUE TITLE
Update IRC password

### ISSUE THREAD

**Issue by micheljung** [FAForever/faf-java-api#201]
Currently, the server updates a user's IRC password every time they log in.
A more sensible solution is to update the IRC password when the user changes the password via the API

**Comment by Brutus5000** [comment]
Is this not working? https://github.com/FAForever/faf-java-api/blob/develop/src/main/java/com/faforever/api/user/UserService.java#L214

**Comment by micheljung** [comment]
oh, i wasn't aware that it's already implemented :)

**Comment by Brutus5000** [comment]
Yes, but it's not in productive use because of website...
