### ISSUE TITLE
Linking to steam is broken

### ISSUE THREAD

**Issue by PhilipJFryFAF** [FAForever/faf-java-api#212]
currently you cannot link your faf acc to steam since you always get an error about your steam ID not being found

i assume this happens because of the somewhat [recent changes](https://steamcommunity.com/games/593110/announcements/detail/1667896941884942467) to the privacy settings in steam

**Comment by axel1200** [comment]
The website uses the python api no? Should be close this?

**Comment by Brutus5000** [comment]
Should be fixed with the latest release.
