### ISSUE TITLE
Global/ladder ratings not created on user activation

### ISSUE THREAD

**Issue by Brutus5000** [FAForever/faf-java-api#223]
This 2 inserts are missing:

https://github.com/FAForever/api/blob/d885c435a52d92adf91c909aa1ab36462b556e41/api/users_route.py#L126

**Comment by micheljung** [comment]
Very sad... this should not be the API's responsibility. We'll add this for now, but as soon as the java-server is deployed (or someone fixes the python server) we should remove this
