### ISSUE TITLE
Gateway Timeout on requesting games

### ISSUE THREAD

**Issue by axel1200** [FAForever/faf-java-api#226]
![image](https://user-images.githubusercontent.com/19996713/40874549-230a16e6-6671-11e8-8cac-190eca16c831.png)
[gay_sex (1).txt](https://github.com/FAForever/faf-java-api/files/2064967/gay_sex.1.txt)

**Comment by Brutus5000** [comment]
This was a side effect of https://github.com/FAForever/faf-java-api/issues/248
