### ISSUE TITLE
User story: Registration blacklist

### ISSUE THREAD

**Issue by Brutus5000** [FAForever/faf-java-api#227]
As a moderator, I want to temporarily ban IP ranges from registration when I notice that an unreasable amount of accounts is generated from this.

As long as the the ban is active, no user from that range should be able to register. The user should be shown an error message instead.

- [ ] [in db] Add a new db table (id, create_time, update_time, ip-range and valid_until)
- [ ] [in api] Add a new elide entity (blacklistRecord)
- [ ] [in api] Add a new error code (IP_IS_BLACKLISTED) along with a check in registration route
- [ ] [in mod client] Add a new list view to see all active blacklist records
- [ ] [in mod client] Add a new button on latest registrations (add to blacklist)

**Comment by govi20** [comment]
Can I take it up? Seems pending since a long time.

**Comment by 1-alex98** [comment]
Why not? Consider joining our Slack, just ask any faf moderator on discord or IRC or send an email to me.

**Comment by Brutus5000** [comment]
This problem was resolved by Steam linking requirement.
