### ISSUE TITLE
Enable force rename player

### ISSUE THREAD

**Issue by axel1200** [FAForever/faf-java-api#257]
https://github.com/FAForever/faf-moderator-client/issues/57

**Comment by axel1200** [comment]
I would also send out an email to the player that he has been renamed and what to

**Comment by basalt79** [comment]
hi
the "force" is to not check

- [minDaysBetweenChange ](https://github.com/FAForever/faf-java-api/blob/36ad69005c6d31cf013a27c7a3e49e36ae468516/src/main/java/com/faforever/api/user/UserService.java#L181)

- [usernameReservationTimeInMonths ](https://github.com/FAForever/faf-java-api/blob/36ad69005c6d31cf013a27c7a3e49e36ae468516/src/main/java/com/faforever/api/user/UserService.java#L187)

so we have to provide a new [changeLogin](https://github.com/FAForever/faf-java-api/blob/36ad69005c6d31cf013a27c7a3e49e36ae468516/src/main/java/com/faforever/api/user/UsersController.java#L75) endpoint in the UserController?

-basalt

**Comment by 1-alex98** [comment]
Yeah it is when users rename to something really bad that we don't tolerate, like "penis1234" idk just something that is unacceptable. As of now they get banned, till the minDaysBetweenChange is run out. And what is also a problem is that moderators need to unban somebody for him to be able to rename. So what a moderator wants to do is simply rename a player forcefully and that is it, maybe give him a warning he gets banned next time he renames to something stupid.

**Comment by 1-alex98** [comment]
Yeah a new method/endpoint call it "forceRename" or anything that fits and validate that the user is a moderator

**Comment by basalt79** [comment]
if i enhance the UserControler, and a moderator has to use this, than the 

- userId of the user which has to be changed
- newUsername

has to be provided, or is this not the right place for the enhancements?

**Comment by 1-alex98** [comment]
Both need to be provided by the caller yes, take in query parameters(@RequestParam) or maybe id as a parameter in the query path (url). I think there is no advantage in any of the both ways.

**Comment by 1-alex98** [comment]
Did you get the slack invite?
@micheljung should have sent one out

**Comment by basalt79** [comment]
@axel1200 thx for the info regards the interface
and until now i have no infos about slack

**Comment by 1-alex98** [comment]
Hmm I will tell him
