### ISSUE TITLE
BanRevokeData can not be posted

### ISSUE THREAD

**Issue by axel1200** [FAForever/faf-java-api#259]
https://github.com/FAForever/faf-moderator-client/issues/3

**Comment by axel1200** [comment]
Maybe if elide does not support this data structure we need to go for a custom controller

**Comment by Brutus5000** [comment]
Jesus no. Just simplify the database from two tables to one. The actual amount of space saved is sooo minimal compared to other tables because we have only a handful of bans.
+ we have a view which joins both tables because you need it together always...

**Comment by axel1200** [comment]
So make a db migration?

**Comment by Brutus5000** [comment]
That would be my suggestion. Add the revocation columns to the ban column. Migrate all existing columns. Delete the old table. Update the view.

**Comment by axel1200** [comment]
Dont need to migrate there is no data in them right :D

**Comment by Brutus5000** [comment]
Of course there is :) There was a time before mordor.
mysql> select count(*) from ban_revoke;
+----------+
| count(*) |
+----------+
|        3 |
+----------+
1 row in set (0.04 sec)

**Comment by Brutus5000** [comment]
Fixed (see db migration V62)
