### ISSUE TITLE
Authorize dialog missing

### ISSUE THREAD

**Issue by axel1200** [FAForever/faf-java-api#265]
![login](https://user-images.githubusercontent.com/19996713/45671095-e03b4e80-bb24-11e8-980a-32ec637b1d7f.gif)
![image](https://user-images.githubusercontent.com/19996713/45671114-ef220100-bb24-11e8-92a5-91e0fa62cd11.png)

**Comment by Brutus5000** [comment]
What happens if you use a private tab and login for the first time? Does it then show the authorize screen?

**Comment by axel1200** [comment]
No it does not show eiter!!!

**Comment by axel1200** [comment]
@Brutus5000 would you be so kind and check the auto-approve-scope field in the oauth-client table and if null or true set it all to false?

**Comment by axel1200** [comment]
https://stackoverflow.com/questions/29696004/skip-oauth-user-approval-in-spring-boot-oauth2

**Comment by axel1200** [comment]
if i think about it pls dont, some clients need to approvement I would say like dl client...

**Comment by axel1200** [comment]
@micheljung so i am a little confused here. We have some clients that need to be auto approved and some that don't need to... how did that work till now? Because there is an auto-approved-scopes field in the db but it seems that is never read and it seems autoApprove is never set in the api and seems to be true by default. Any way with DLC secret being public and needs to auto approved the authorize dialog is "not needed" security anyway.

**Comment by micheljung** [comment]
The "Authorize" dialog is not supposed to show up for the website, we explicitly disabled it as the website is trusted. However, after logging out, on login the "Login" form should show
