### ISSUE TITLE
Implement username/password change, password reset

### ISSUE THREAD

**Issue by micheljung** [FAForever/faf-java-api#35]

**Comment by Geosearchef** [comment]
unit tests missing

**Comment by micheljung** [comment]
Since the password is currently only sha256'd and might, therefore, be read and converted to plaintext by an attacker, we should encrypt the JWT payload

**Comment by Geosearchef** [comment]
not relevant for password reset, but for registration

**Comment by IDragonfire** [comment]
What is the state of this?

**Comment by Geosearchef** [comment]
nearly complete, I will finish as soon as I get access to a computer I can test on (should be the next 2-3 days).

**Comment by IDragonfire** [comment]
Do you need help with something? 

PS.: https://github.com/FAForever/faf-java-api/issues/76#issuecomment-300061710

**Comment by Geosearchef** [comment]
no, should be done, just hadn't got enough time, thx

**Comment by Brutus5000** [comment]
Finally :)

**Comment by micheljung** [comment]
Hooray! :) Many thanks.
