### ISSUE TITLE
BanTable loaded on every requeset

### ISSUE THREAD

**Issue by IDragonfire** [FAForever/faf-java-api#49]
`FafUserDetails` needs to know if the account is banned, for this reason we query this table (if not cached) on every request ...

**Comment by micheljung** [comment]
Correct me if I'm wrong, but it's only loaded on login. That's what we have JWT for.

**Comment by IDragonfire** [comment]
https://github.com/FAForever/faf-java-api/blob/develop/src/main/java/com/faforever/api/security/FafUserDetails.java#L21

**Comment by micheljung** [comment]
You're still not saying anything

**Comment by IDragonfire** [comment]
That the line that cause the load of the ban table

**Comment by micheljung** [comment]
Yes, and that line is only called on login. As I said before.

**Comment by micheljung** [comment]
Closing as there is no appearent problem or suggestion.
