### ISSUE TITLE
Rework OAuth: Scopes and Co

### ISSUE THREAD

**Issue by IDragonfire** [FAForever/faf-java-api#68]
```java
public class OAuthClientDetails extends BaseClientDetails {

  public OAuthClientDetails(OAuthClient oAuthClient) {
    super(oAuthClient.getId(),
        null,
        oAuthClient.getDefaultScope().replace(' ', ','),
        // FIXME read from database instead of hardcoding (but DB migration is required)
        "authorization_code,refresh_token,implicit,password,client_credentials",
        null);
    setClientSecret(oAuthClient.getClientSecret());
  }
}
```
https://github.com/FAForever/faf-java-api/blob/v0.5.0/src/main/java/com/faforever/api/security/OAuthClientDetails.java#L16

- [x] Where to store app names or passed by app? (currently using `name` column of `oauth_clients`)
- [x] Where to store allowed scopes/permissions? (currently a ` ` (space)  seperated column `default_scope` in `oauth_clients`
- [x] Who is responsible for the scope? client can provide `scope` attribute and we have `default_scope` in database
- [ ] Add OAuth scopes to all routes/entities
- [x] What about the `resourceIDs` param?
- [x] What about the `authorities` param?
- [x] We should check the redirect url, or is the `redirectUris` [param]enough? 

When I say "param" I mean http://docs.spring.io/spring-security/oauth/apidocs/org/springframework/security/oauth2/provider/client/BaseClientDetails.html#BaseClientDetails(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)

Related https://github.com/FAForever/faf-java-api/pull/61

**Comment by IDragonfire** [comment]
scope should be a comma seperated list
![image](https://cloud.githubusercontent.com/assets/1217999/26287210/c3fc8f58-3e76-11e7-8149-3a2d45669b9a.png)
http://projects.spring.io/spring-security-oauth/1.x/docs/oauth2.html

**Comment by micheljung** [comment]
Unfortunately, Spring [is wrong on this](https://tools.ietf.org/html/rfc6749#section-3.3).
> The value of the scope parameter is expressed as a list of space-delimited, case-sensitive strings.

* What's wrong with storing the allowed scopes as a space separated column? (it follows the OAuth specs)
* The Authorization server specifies what scopes a client is allowed to request, what the default is when it doesn't request anything, and the client is free to request any scopes it wants from the list of its allowed scopes. But that's all written in the OAuth specs so I'm not sure why I'm even explaining this here
* The resource server and the authorization server are the same in our case, so we don't need resourceIDs.
* [authorities: Authorities that are granted to the client (regular Spring Security authorities).](http://projects.spring.io/spring-security-oauth/docs/oauth2.html#configuring-client-details)
* Redirect URIs needed to be added

**Comment by bukajsytlos** [comment]
In our case default scopes eq allowed scopes.

**Comment by micheljung** [comment]
Yes, for what we have now. Doesn't mean it will always be like this, and even if... does it matter? :-)
