### ISSUE TITLE
Tests Compare JSON Documents

### ISSUE THREAD

**Issue by IDragonfire** [FAForever/faf-java-api#69]
- [ ] Use `HttpStatus.UNPROCESSABLE_ENTITY.toString())`
- [ ] Use no string, instead a constraint or method from somewhere
- [ ] Use `JSONPath` 

https://github.com/FAForever/faf-java-api/wiki/Testing#compare-json

We have currently different ways ...

e.g. 

```java
  String expected = String.format("{\"player\":{\"id\":%s,\"login\":\"%s\"},\"clan\":null}",
        me.getId(),
        me.getLogin());

    this.mvc.perform(get("/clans/me/")
        .header("Authorization", accessToken))
        .andExpect(content().string(expected))
        .andExpect(status().isOk());
```

or 

```java
 this.mvc.perform(fileUpload("/maps/upload"))
      .andExpect(status().is(400))
      .andExpect(content().json(
        "{\n" +
          " \"errors\": [\n" +
          "   {\n" +
          "     \"status\": \"400\",\n" +
          "     \"title\": \"org.springframework.web.multipart.support.MissingServletRequestPartException\",\n" +
          "     \"detail\": \"Required request part 'file' is not present\"\n" +
          "   }\n" +
          " ]\n" +
          "}"
      ));
```

Should we use a libary like?

* https://github.com/hertzsprung/hamcrest-json
* https://github.com/skyscreamer/JSONassert#error-messages

Parent Issue: https://github.com/FAForever/faf-java-api/issues/50

**Comment by IDragonfire** [comment]
# My View
I highly recommand to use string comparsion instead of `json` Matchers
1. `json` Matcher detect not changes inside the array ... e.g. you can delete an attribute and the test pass
2. `json` Matcher is a additional libary to maintaince and learn
3. keep it simple, just to string comparison ...

**Comment by IDragonfire** [comment]
# After Discussion

1. What is with `unpredictable` fields, e.g. timestamps?
2. What is with escaping?

**Comment by bukajsytlos** [comment]
What do you think about using json path assertions? Like [here](https://github.com/FAForever/faf-java-api/pull/56/files#diff-20250a3afda055cf653451aad249c491)

**Comment by IDragonfire** [comment]
JSON PATH is okay ;)
If all PR get merged I will refactor all tests ...

**Comment by micheljung** [comment]
Looks like the PRs got merged and this is ready to be refactored :)

**Comment by IDragonfire** [comment]
Not sure if all tets now use JSON PATH ...

**Comment by Brutus5000** [comment]
jsonPath is the way to go.
