### ISSUE TITLE
Implement Permission

### ISSUE THREAD

**Issue by IDragonfire** [FAForever/faf-java-api#81]
As soon as we have some kind of permission system in the database, we have to implement it in the java-api 

https://github.com/FAForever/db/pull/76
https://github.com/FAForever/faf-java-api/pull/46

**Comment by micheljung** [comment]
AFAIK the permission system is available in the database

**Comment by Brutus5000** [comment]
Looking at this PR https://github.com/FAForever/db/pull/76 I would say this is not the case.

**Comment by IDragonfire** [comment]
If you count the `lobby_admin` as permisison system ...
Otherwise nobody implemented a `real` permission system ...

**Comment by micheljung** [comment]
Alright, I thought we merged FAForever/db#76
