### ISSUE TITLE
Formatting Issue

### ISSUE THREAD

**Issue by IDragonfire** [FAForever/faf-java-api#82]
Since the merge yesterday I have some formatting issues in my pr's.
It look like my IDE was not configured correctly, but ` .editorconfig` (https://github.com/FAForever/faf-java-api/commit/b7276e8fcdc9e814a775858f60bed7f0d6bc2b98#diff-1e70daafb475c0ce3fef7d2728279182) solves this ...

# Current Situation
Some java files are wrong formatted (4 spaces instead of 2). Auto-Formatter will do the job, but merge request diff will increase.

Should we do a format commit if all Pr's are merged?

**Comment by Brutus5000** [comment]
Closed due to inactivity.
